version: '3.0'

services:
 postgres:
  image: postgres:latest
  ports:
   - "5432:5432"
  restart: always
  environment:
      - POSTGRES_PASSWORD=senhateste
      - POSTGRES_USER=usuarioteste
      - POSTGRES_DB=gestaodb

 express: 
  build: .
  ports:
  - "3001:3001"
  links:
  - postgres
  restart: always
  environment:
      - NODE_ENV=production
      - DB_USER=usuarioteste
      - DB_PASS=senhateste
      - DB_NAME=gestaodb
      - DB_HOST=postgres
      - PORT=3001